#!/usr/bin/env bash
# ============================================================
# Git configuration checks.
# ============================================================
#
# Git settings are never modified automatically. Signing keys and
# credentials are exactly the category of change that must stay under
# human control, and the rest of the git configuration is generated by
# chezmoi, so writing it here would only create drift.
# ============================================================

git::config() {
    git config --global --get "$1" 2>/dev/null
}

git::expect() {
    local key="$1"
    local want="$2"
    local label="$3"
    local actual

    actual="$(git::config "$key")"

    if [ "$actual" = "$want" ]; then
        integration::ok "$label" "$actual"
        return 0
    fi

    if [ -z "$actual" ]; then
        integration::warn "$label" "not set" "$want"
    else
        integration::warn "$label" "$actual" "$want"
    fi

    report::fix "$label" "git config --global $key $want" manual
}

integration::git_defaults() {
    git::expect pull.rebase true "git → pull.rebase"
    git::expect fetch.prune true "git → fetch.prune"
    git::expect init.defaultBranch main "git → default branch"

    local editor
    editor="$(git::config core.editor)"
    if [ -n "$editor" ]; then
        integration::ok "git → editor" "$editor"
    else
        integration::warn "git → editor" "not set" "nvim"
        report::fix "git → editor" "git config --global core.editor nvim" manual
    fi
}

integration::git_delta() {
    local pager
    pager="$(git::config core.pager)"

    case "$pager" in
        *delta*)
            integration::ok "git → delta" "pager configured"
            ;;
        "")
            integration::warn "git → delta" "core.pager not set"
            report::fix "git → delta" "git config --global core.pager delta" manual
            ;;
        *)
            integration::warn "git → delta" "pager is $pager"
            report::fix "git → delta" "git config --global core.pager delta" manual
            ;;
    esac
}

# Signing is intentionally advisory only.
integration::git_signing() {
    local signing format key

    signing="$(git::config commit.gpgsign)"
    format="$(git::config gpg.format)"
    key="$(git::config user.signingkey)"

    if [ "$signing" != "true" ]; then
        integration::warn "git → commit signing" "disabled"
        report::fix "git → commit signing" "dev setup git-signing" manual
        return 0
    fi

    if [ "$format" != "ssh" ]; then
        integration::warn "git → commit signing" "enabled, format is ${format:-gpg}" "ssh"
        report::fix "git → commit signing" "dev setup git-signing" manual
        return 0
    fi

    if [ -z "$key" ]; then
        integration::warn "git → commit signing" "no signing key selected"
        report::fix "git → commit signing" "dev setup git-signing" manual
        return 0
    fi

    integration::ok "git → commit signing" "ssh"
}

integration::git_ignore() {
    local path
    path="$(git::config core.excludesfile)"

    if [ -n "$path" ] && [ -f "$(path::expand "$path")" ]; then
        integration::ok "git → global ignore" "configured"
    else
        integration::warn "git → global ignore" "not configured"
        report::fix "git → global ignore" \
            "git config --global core.excludesfile ~/.config/git/ignore" manual
    fi
}

integration::gh_auth() {
    if run::limited 10 gh auth status >/dev/null 2>&1; then
        integration::ok "gh → auth" "authenticated"
    else
        integration::warn "gh → auth" "not authenticated"
        report::fix "gh → auth" "gh auth login" manual
    fi
}
